### ISSUE TITLE
Add User-Agent header when performing oEmbed request

### ISSUE THREAD

**Issue by equinox7** [punkave/oembetter#3]
Facebook [supports oEmbed](https://developers.facebook.com/blog/post/2015/12/14/embedded-video-api-oembed/). But your module returns an error: "XML response lacks oembed element".
It is because request is without User-Agent and Facebook returns an HTML page that says, that browser is unsupported.
Please add User-Agent header when performing oEmbed request.

**Comment by boutell** [comment]
A pull request for this would be welcome.

On Fri, Apr 15, 2016 at 5:08 AM, Andrew <notifications@github.com> wrote:

> Facebook supports oEmbed
> <https://developers.facebook.com/blog/post/2015/12/14/embedded-video-api-oembed/>.
> But your module returns an error: "XML response lacks oembed element".
> It is because request is without User-Agent and Facebook returns an HTML
> page that says, that browser is unsupported.
> Please add User-Agent header when performing oEmbed request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/oembetter/issues/3>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
